### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by tbabej** [matrix-org/matrix-search#1]
Hi,

thanks for the good work! Is the deamon in alpha-functional state atm, and can be tested out, or is further integration with local riot client needed?

**Comment by t3chguy** [comment]
So Riot has no support for it yet, you have to modify js-sdk and react-sdk to connect to the daemon, and it is not quite usable yet, https://github.com/matrix-org/matrix-search/tree/two-headed-js-go is the ongoing work

**Comment by MountainX** [comment]
Any further updates?

**Comment by TheTimeWalker** [comment]
So it seems like there hasn't been work here for quite a while. Since some issues mention this library for true E2E search capabilities, is there still work or interest in this search daemon project? Or are there other plans on how to enhance the search function in Matrix?

**Comment by t3chguy** [comment]
Work has moved to https://github.com/matrix-org/pantalaimon
